### ISSUE TITLE
Mining with constants - InvocationTargetException

### ISSUE THREAD

**Issue by kliegr** [lajus/amie#27]
I am trying to run a small toy dataset with 16 triples
[sample.nt.zip](https://github.com/lajus/amie/files/4817691/sample.nt.zip)
. 
When I run 

    java -jar amie-dev.jar -d" " -mins 1 -minis 1 sample.nt

I get four rules.

But when I add the -const option

    java -jar amie-dev.jar -d" " -mins 1 -minis 1 -const sample.nt

I get 

java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at amie.mining.assistant.MiningAssistant.applyMiningOperators(MiningAssistant.java:1391)
        at amie.mining.AMIE$RDFMinerJob.run(AMIE.java:419)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: The query  => ?a  <https://w3id.org/biolink/vocab/interacts_with>  <http://ensembl.org/id/G> does not contain fresh variables in the last triple pattern.
        at amie.mining.assistant.MiningAssistant.getInstantiatedAtoms(MiningAssistant.java:793)

**Comment by lajus** [comment]
Hi,

I have not updated amie-dev.jar in a while and I will probably remove it (in favor of github "actions") in the near future. I would advise to recompile the project using maven or using a release.

Cheers,
Jonathan
